language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

install:
  - npm install -q --no-color --no-progress

script:
  - npm test -- --coverage --watchAll=false # Include coverage when running tests

after_script: # Upload coverage reports
  - npm run coveralls

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: netlify
  site: $NETLIFY_SITE_ID
  auth: $NETLIFY_ACCESS_TOKEN
  dir: ./build
  skip_cleanup: true
  on:
    branch: develop
