sudo: false 

language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

script:
  - npm test -- --coverage --watchAll=false # Include coverage when running tests

  env:
    - CI=true   

after_script: # Upload coverage reports
    - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir ./build
  skip_cleanup: true
  on:
    branch: develop
